### ISSUE TITLE
remove the administrator

### ISSUE THREAD

**Issue by rashxxl** [steinwurf/adb-join-wifi#13]
How do I remove the administrator I issued adb-join-wifi to?
privileges were issued by the command: adb shell dpm set-device-owner "com.steinwurf.adbjoinwifi/.AdminReceiver" 
Now I can't delete

**Comment by jpihl** [comment]
Did you try this?

```adb shell am start -n com.steinwurf.adbjoinwifi/.MainActivity -e clear_device_admin true```

**Comment by rashxxl** [comment]
> 

It worked! Thanks!
