### ISSUE TITLE
adb-join-wifi requires to allow from popup

### ISSUE THREAD

**Issue by ashutoshtiwari199** [steinwurf/adb-join-wifi#14]
Hi, 
I am using this app to connect/disconnect wifi, but in huawei china version is showing the popup to allow the permission to connect wifi.

Popup message: **adb-join wants to connect wifi _name_** 

Suggest me the way to handle this.

Thanks.

**Comment by jpihl** [comment]
Hi Ashutosh,

I don't have access to a Huawei china device, so I don't have any advice for you. Maybe this is just not possible of this category of devices. If you do find a way to get this working please share your findings and I can make them available in the readme of this project.

All the best,

Jeppe

**Comment by ashutoshtiwari199** [comment]
Hi Jphil,

Actually I didn't  found the direct solution but somehow I managed popup with adb keyevent (tab, eneter).

Thanks!
