### ISSUE TITLE
SSID with space

### ISSUE THREAD

**Issue by thlengane** [steinwurf/adb-join-wifi#9]
Hi
My wifi SSID has a space in it.  When I try to join it, it only picks up the first word of the SSID before the space. How can I escape the space?

See below:
**COMMAND**
adb -s AQH7N17B18019814 shell am start -n com.steinwurf.adbjoinwifi/.MainActivity -e ssid "**MY 5G_OFFICE**" -e password_type WEP -e password mypassword

**RESPONSE**
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] pkg=**5G_OFFICE** cmp=com.steinwurf.adbjoinwifi/.MainActivity (has extras) }

On the app itself, it is connecting to the wifi called "**MY**", the first word of the SSID.

**Comment by parkerlreed** [comment]
Try with a \ in front of the space without the quotes

**Comment by thlengane** [comment]
> Try with a \ in front of the space without the quotes

Beautiful, it worked. Thanks for the quick reply.
